### ISSUE TITLE
feat: add support for loader data

### ISSUE THREAD

**Issue by kiliman** [kentcdodds/remix-mdx#1]
Given the following MDX frontmatter:
```yaml
---
title: My super First Post
description: Isn't this awesome?
meta:
  title: My Blog - ${data.title}
  charset: utf-8
headers:
  Cache-Control: no-cache
---
```
I've got it outputting the following:
```js
export function meta({data}) {
  return {
    title: `My Blog - ${data.title}`,
    description: data.description,
    charset: `utf-8`
  };
}
export function loader() {
  return json(
    {
      title: "My super First Post",
      description: "Isn't this awesome?"
    }, 
    { headers: { 'Cache-Control': 'no-cache' } });
}
```
NOTE: If you don't include `meta` in frontmatter, then it will automatically generate the meta object if you include any of the following keys: `title`, `description`, `keywords`.

If you include `meta`, then you can override the loader data, with a template string, or hard-coded value. You can also include any key (e.g., charset)

If you include `headers`, then it will include the headers object in the `loader` function.

Anyway, let me know what you think.
